### ISSUE TITLE
Only use one of the compoenents

### ISSUE THREAD

**Issue by andrantis** [Addepar/ember-widgets#216]
Is there a way to only use one of the components without importing the whole library? Like only importing  the select component. What would be the right approach to do this?

**Comment by cyril-sf** [comment]
Hi @andrantis,

There is currently no way of doing this automatically/easily.
We currently have a project in flight that will help solve that problem.

**Comment by andrantis** [comment]
I see. Thank you. I'll probably do that until the new project is ready. Thanks again.
