### ISSUE TITLE
Confused on how to add to ember-cli project

### ISSUE THREAD

**Issue by jdhines** [Addepar/ember-widgets#218]
I read through the readme, but I'm still not sure how really to install and use it. With other components I've just done `ember install <whatever>` but that type of command wasn't in the instructions.

I did a `bower install ember-widgets` which also installed the dependencies (lodash, list-view, etc) so I'm not sure what in the Readme is applicable when it mentions "build for ember-cli" when all I want to do is use the components.
After doing the Bower install, I still get an error of 

`A helper named 'select-component' could not be found`

Using Ember 1.11

**Comment by mattlindsey** [comment]
I'm getting same error on ember 1.11.3 ('A helper named `popover-link-component` not found') so tried upgrading to ember 1.13.8, but then I get 'ECONFLICT Unable to find suitable version for ember' error trying to install ember-widgets.

**Comment by jdhines** [comment]
Is this project even alive anymore, or is ember-widgets dead? That search box on select elements is brilliant, but I can't get it to work, either by just installing via bower or including them in `ember-cli-build.js` (formally brocfile.js)

**Comment by cbornhoft** [comment]
This widget is meant for ember <1.12 since it uses ListView, which was replaced by [Ember Collections](https://github.com/emberjs/list-view#compatibility) as of 1.13.

**Comment by cyril-sf** [comment]
We are in the process of converting Ember Widgets to an Ember-CLI addon.

**Comment by cyril-sf** [comment]
Ember Widgets is now an ember-cli addon. Closing this for now.
