### ISSUE TITLE
Support custom css classes for header/body/footer in modal component

### ISSUE THREAD

**Issue by shaoster** [Addepar/ember-widgets#277]
In certain cases, I want to provide custom styling for a specific modal dialog box, and being able to tag the header/body/footer with a css class makes targeting that styling much more user-friendly.

**Comment by shaoster** [comment]
This would likely just be providing some extra configurability to https://github.com/Addepar/ember-widgets/blob/master/app/templates/modal.hbs

**Comment by mixonic** [comment]
I believe this was closed by https://github.com/Addepar/ember-widgets/pull/278, please re-open if I'm wrong!
