### ISSUE TITLE
How do I use this with the ember-cli?

### ISSUE THREAD

**Issue by balupton** [Addepar/ember-widgets#76]
I added the following to my Brocfile:

```
app.import('vendor/ember-widgets/dist/js/ember-widgets.js')
app.import('vendor/ember-widgets/dist/css/ember-widgets.css')
```

Then did this in my template:

```
{{multi-select-component contentBinding="this" optionLabelPath="name"   optionValuePath="id" classNames="multi-select-example"}}
```

But I get the error:

```
Uncaught TypeError: Cannot read property 'extend' of undefined
on
Ember.Widgets.SelectOptionView = Ember.ListItemView.extend({
```

And: 

```
Uncaught Error: <myapp@view:default::ember391> Handlebars error: Could not find property 'multi-select-component' on object (generated posts controller). 
```

**Comment by hy-brasil** [comment]
Sorry for newbie question here... but to use this in ember-cli... 
I just copy the entire code into the vendor folder is it? 
The app, the bin etc etc.. and then just app.include from the dist like balupton did above yeah?
Thanks

**Comment by igillis** [comment]
I think what @balupton did was to check out this project, build it, and copy just the `dist` folder into his `vendor/` folder.

We're also working on https://github.com/Addepar/ember-widgets/tree/igillis/ember-cli right now and hope to have it published soon.

**Comment by hy-brasil** [comment]
Ok, thanks very much, I'll have a go at that.
